/* List of defines generated by configure. Included with preprocessor flag,
 * -include, to avoid long list of -D defines on the compile command-line.
 * Do not edit.
 */

#ifndef js_confdefs_h
#define js_confdefs_h

// Expands to all the defines from configure.
#define CROSS_COMPILE 
#define EARLY_BETA_OR_EARLIER 1
#define EDITLINE 1
#define ENABLE_INTL_API 1
#define ENABLE_TESTS 1
#define ENABLE_TYPED_OBJECTS 1
#define ENABLE_WASM_BULKMEM_OPS 1
#define ENABLE_WASM_CRANELIFT 1
#define ENABLE_WASM_GC 1
#define ENABLE_WASM_REFTYPES 1
#define GTEST_HAS_RTTI 0
#define HAVE_64BIT_BUILD 1
#define HAVE_ALLOCA_H 1
#define HAVE_CPUID_H 1
#define HAVE_DIRENT_H 1
#define HAVE_GETC_UNLOCKED 1
#define HAVE_GETOPT_H 1
#define HAVE_GMTIME_R 1
#define HAVE_INTTYPES_H 1
#define HAVE_LANGINFO_CODESET 1
#define HAVE_LIBM 1
#define HAVE_LOCALECONV 1
#define HAVE_LOCALTIME_R 1
#define HAVE_NETINET_IN_H 1
#define HAVE_NL_TYPES_H 1
#define HAVE_POSIX_MEMALIGN 1
#define HAVE_PTHREAD_GETNAME_NP 1
#define HAVE_SSIZE_T 1
#define HAVE_STDINT_H 1
#define HAVE_STRNDUP 1
#define HAVE_SYS_MOUNT_H 1
#define HAVE_SYS_QUEUE_H 1
#define HAVE_SYS_STATVFS_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_THREAD_TLS_KEYWORD 1
#define HAVE_TM_ZONE_TM_GMTOFF 1
#define HAVE_UNISTD_H 1
#define HAVE_VALLOC 1
#define HAVE_VA_COPY 1
#define HAVE_VA_LIST_AS_ARRAY 1
#define HAVE_VISIBILITY_ATTRIBUTE 1
#define HAVE_VISIBILITY_HIDDEN_ATTRIBUTE 1
#define HAVE___CXA_DEMANGLE 1
#define JS_64BIT 1
#define JS_BUILD_BINAST 1
#define JS_CODEGEN_X64 1
#define JS_DEBUG 1
#define JS_DEFAULT_JITREPORT_GRANULARITY 3
#define JS_GC_ZEAL 1
#define JS_JITSPEW 1
#define JS_MASM_VERBOSE 1
#define JS_PUNBOX64 1
#define JS_STANDALONE 1
#define JS_STRUCTURED_SPEW 1
#define JS_TRACE_LOGGING 1
#define JS_WITHOUT_NSPR 1
#define MALLOC_H <malloc/malloc.h>
#define MALLOC_USABLE_SIZE_CONST_PTR const
#define MOZILLA_UAVERSION "70.0"
#define MOZILLA_VERSION "70.0a1"
#define MOZILLA_VERSION_U 70.0a1
#define MOZJS_MAJOR_VERSION 70
#define MOZJS_MINOR_VERSION 0
#define MOZ_BUILD_APP js
#define MOZ_DEBUG 1
#define MOZ_DEBUG_RUST 1
#define MOZ_DLL_PREFIX "lib"
#define MOZ_DLL_SUFFIX ".dylib"
#define MOZ_MEMORY 1
#define MOZ_PROFILING 1
#define MOZ_UPDATE_CHANNEL default
#define NIGHTLY_BUILD 1
#define NO_NSPR_10_SUPPORT 1
#define STDC_HEADERS 1
#define U_STATIC_IMPLEMENTATION 1
#define U_USING_ICU_NAMESPACE 0
#define VA_COPY va_copy
#define WASM_CODEGEN_DEBUG 1
#define WASM_PRIVATE_REFTYPES 1
#define XP_DARWIN 1
#define XP_MACOSX 1
#define XP_UNIX 1
#define X_DISPLAY_MISSING 1

#include "js/RequiredDefines.h"

#endif /* js_confdefs_h */
