/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pwootage_oc_js_DuktapeEngine */

#ifndef _Included_com_pwootage_oc_js_DuktapeEngine
#define _Included_com_pwootage_oc_js_DuktapeEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pwootage_oc_js_DuktapeEngine
 * Method:    createContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pwootage_oc_js_DuktapeEngine_createContext
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
